name: things_todo
description: A new Flutte r  project.
version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=2.19.0 <3.0.0"
dependencies:
  bloc: ^8.1.0
  colorful_print: ^0.1.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  freezed_annotation: ^2.2.0
  get: ^4.6.5
  get_it: ^7.2.0
  injectable: ^2.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  json_annotation: ^4.8.0
  nb_utils: ^4.6.25
  onbackground_shared_prefrences: ^0.0.2
  responsive_framework: ^0.2.0
dev_dependencies:
  build_runner: ^2.4.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.3
  json_serializable: ^6.6.0
flutter:
  assets:
    - assets/images/
  fonts:
    - family: Alexandria
      fonts:
        - asset: assets/fonts/AlexandriaFLF.ttf
        - asset: assets/fonts/AlexandriaFLF-Italic.ttf
          style: italic
        - asset: assets/fonts/AlexandriaFLF-Bold.ttf

  uses-material-design: true
flutter_intl:
  arb_dir: assets/l10n
  class_name: AppLocalizations
  enabled: true
  main_locale: en
  output_dir: lib/generated
